# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  # <ecdf_compare_niche>
  # <ecdf_nonnormal_niche>
  # <ecdf_theoretical_niche>
  # <create_distance_suitability_plot>
  # <run_ecdf_mahal_analysis>
  ".data",
  # <ecdf_nonnormal_niche>
  "data",
  NULL
))
