# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  ".data", # <ecdf_compare_niche>
  ".data", # <ecdf_nonnormal_niche>
  "data", # <ecdf_nonnormal_niche>
  ".data", # <ecdf_theoretical_niche>
  ".data", # <create_distance_suitability_plot>
  ".data", # <run_ecdf_mahal_analysis>
  NULL
))
