# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "Sample_Size", # <ecdf_niche>
  "Correlation", # <ecdf_niche>
  "Method", # <ecdf_niche>
  "Mahalanobis_Distance", # <create_distance_suitability_plot>
  "Niche_Suitability", # <create_distance_suitability_plot>
  "ChiSquared_suitability", # <create_distance_suitability_plot>
  "ECDF_suitability", # <create_distance_suitability_plot>
  "Variable_1", # <run_ecdf_mahal_analysis>
  "Variable_2", # <run_ecdf_mahal_analysis>
  "Niche_suitability", # <run_ecdf_mahal_analysis>
  "ChiSquared_suitability", # <run_ecdf_mahal_analysis>
  "ECDF_suitability", # <run_ecdf_mahal_analysis>
  NULL
))
